### PR TITLE
Bugfix/missing xstream exception

### PR DESCRIPTION
**Pull request by martink76**

### CODE REVIEW

**Review by smcvb — CHANGES_REQUESTED** [review]
The changes look good, but I still have one request to make. We want to release this in 4.5.1 and for that, the PR should be merged into `axon-kafka-4.5.x`. If you could make that adjustment, @martink76, then we should be good to go.

**Comment by martink76** [comment]
@smcvb Thanks for the feedback. I've rebased onto axon-kafka-4.5.x.
Happy to hear that a 4.5.1 release is planned 👍

**Review by lfgcampos — APPROVED** [review]

**Comment by martink76** [comment]
Just to be sure - is there anything left I can do for this PR?

**Review by smcvb — APPROVED** [review]
My concerns have been addressed, hence approving.

**Comment by smcvb** [comment]
> Just to be sure - is there anything left I can do for this PR?

Yep, that was getting my attention. :sweat_smile: 
My apologies for the wait; I think we're good to merge.

Thanks for the effort here, @martink76.
Any help is always very much appreciated! :-)

**Comment by martink76** [comment]
@smcvb @lfgcampos Thank you for the support :+1:

**Pull request merged**
